export const tiposTareas = {
  BUSCAR_TAREAS_PENDIENTE: 'BUSCAR_TAREAS_PENDIENTE',
  BUSCAR_TAREAS_TERMINADA: 'BUSCAR_TAREAS_TERMINADA',
  BUSCAR_TAREAS_RECHAZADA: 'BUSCAR_TAREAS_RECHAZADA',
  NUEVA_TAREA: 'NUEVA_TAREA',
  GUARDAR_TAREA: 'GUARDAR_TAREA',
  BUSCAR_TAREAS_POR_ID_PENDIENTE: 'BUSCAR_TAREAS_POR_ID_PENDIENTE',
  BUSCAR_TAREAS_POR_ID_TERMINADA: 'BUSCAR_TAREAS_POR_ID_TERMINADA',
  BUSCAR_TAREAS_POR_ID_RECHAZADA: 'BUSCAR_TAREAS_POR_ID_RECHAZADA',
  ACTUALIZAR_TAREA: 'ACTUALIZAR_TAREA',
  ELIMINAR_TAREA: 'ELIMINAR_TAREA'
};
